export const autos = [
  {
    id: 1,
    marca: "Porsche",
    modelo: "911 Carrera GTS",
    anio: 2025,
    motor: "3.6L Bóxer Turbo",
    potencia: "532 HP",
    combustible: "Nafta",
    transmision: "PDK 8 velocidades",
    precio: 165000,
    color: "Gris GT",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Porsche Centro Montevideo",
    descripcion: "Ícono deportivo con motor bóxer trasero y tecnología híbrida T-Hybrid.",
    imagen: "https://imgs.search.brave.com/MEjC45Tl5Kx_lhgizHchDcAZWNwr7SII7yF3flOvW0c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wb3Jz/Y2hlcGljdHVyZXMu/Zmxvd2NlbnRlci5k/ZS9wbWRiL3RodW1i/bmFpbC5jZ2k_aWQ9/MjgwNTU2Jnc9MTkz/NSZoPTEwODkmY3Jv/cD0xJnB1YmxpYz0x/JmNzPTg1ZTcwODJl/MDQwMTQ2ODY"
  },
  {
    id: 2,
    marca: "Tesla",
    modelo: "Model S Plaid",
    anio: 2025,
    motor: "Tres motores eléctricos",
    potencia: "1020 HP",
    combustible: "Eléctrico",
    transmision: "Automática",
    precio: 95000,
    color: "Blanco Perlado",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Tesla Store (importación directa)",
    descripcion: "Sedán eléctrico de altísimas prestaciones, 0-100 km/h en menos de 2 segundos.",
    imagen: "https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Model-S-Hero-Desktop-US-v2.jpg"
  },
  {
    id: 3,
    marca: "BMW",
    modelo: "M3 Competition",
    anio: 2025,
    motor: "3.0L TwinPower Turbo I6",
    potencia: "523 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 82000,
    color: "Frozen Tampa Bay Green",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "BMW Motorrad Uruguay",
    descripcion: "Sedán deportivo de alto rendimiento, tracción trasera, ideal para pista y calle.",
    imagen: "https://imgs.search.brave.com/fxum48Tu8nVb99Jr-9gIq3ylfxAH0aqJRoWgr66vW3w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/Ym13YmxvZy5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjQv/MDUvMjAyNS1ibXct/bTMtZnJvemVuLXRh/bXAtYmF5LTAzLTgz/MHg2MjMuanBn"
  },
  {
    id: 4,
    marca: "Honda",
    modelo: "Civic Type R",
    anio: 2025,
    motor: "2.0L VTEC Turbo",
    potencia: "329 HP",
    combustible: "Nafta",
    transmision: "Manual 6 velocidades",
    precio: 48000,
    color: "Rojo Championship",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Honda Uruguay",
    descripcion: "Hatchback deportivo de tracción delantera con récord en Nürburgring en su categoría.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 5,
    marca: "Lamborghini",
    modelo: "Revuelto",
    anio: 2025,
    motor: "6.5L V12 Híbrido",
    potencia: "1001 HP",
    combustible: "Híbrido",
    transmision: "Automática 8 velocidades",
    precio: 610000,
    color: "Verde Citrea",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Punta del Este, Uruguay",
    vendedor: "Lamborghini Boutique (importación exclusiva)",
    descripcion: "Superdeportivo híbrido enchufable, sucesor del Aventador, con tres motores eléctricos.",
    imagen: "https://imgs.search.brave.com/kwRTIOaxPOJPYPMU5e3HKf0FQuR1JOFlp-p8ZXcGbho/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kaS11/cGxvYWRzLXBvZDQy/LmRlYWxlcmluc3Bp/cmUuY29tL2xhbWJv/cmdoaW5pYnJvd2Fy/ZC91cGxvYWRzLzIw/MjMvMDQvUmV2dWVs/dG8xLnBuZw"
  },
  {
    id: 6,
    marca: "Toyota",
    modelo: "GR Corolla",
    anio: 2025,
    motor: "1.6L Turbo 3 cilindros",
    potencia: "300 HP",
    combustible: "Nafta",
    transmision: "Manual 6 velocidades",
    precio: 39000,
    color: "Blanco Ártico",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Toyota del Uruguay",
    descripcion: "Hatchback deportivo con tracción integral GR-Four y caja manual de 6 marchas.",
    imagen: "https://imgs.search.brave.com/88AdJ95kQAOp_NdUADAB3O3QbM-yBaHjTRYskvvXGP0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL210Zy1wcm9k/LzY4ZDQ3ODlkYWEz/OWI4MDAwMmI2ODRm/NC8yMDI2LXRveW90/YS1nci1jb3JvbGxh/LXByZW1pdW0tcGx1/cy1hdC1zdXBlcnNv/bmljcmVkLTAxNC5q/cGc_dz03Njgmd2lk/dGg9NzY4JnE9NzUm/Zm9ybWF0PXdlYnA"
  },
  {
    id: 7,
    marca: "Mercedes-Benz",
    modelo: "AMG GT 63",
    anio: 2025,
    motor: "4.0L V8 Biturbo",
    potencia: "577 HP",
    combustible: "Nafta",
    transmision: "Automática 9 velocidades",
    precio: 180000,
    color: "Negro Obsidiana",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Buenos Aires, Argentina",
    vendedor: "Mercedes-Benz AMG Performance Center",
    descripcion: "Gran turismo de 4 puertas con carrocería de fibra de carbono opcional.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 8,
    marca: "Ford",
    modelo: "Mustang Dark Horse",
    anio: 2025,
    motor: "5.0L V8 Coyote",
    potencia: "500 HP",
    combustible: "Nafta",
    transmision: "Manual 6 velocidades",
    precio: 62000,
    color: "Gris Vapor",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Ford Uruguay",
    descripcion: "Versión de altas prestaciones del Mustang, orientada a uso en pista.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 9,
    marca: "Audi",
    modelo: "RS5 Sportback",
    anio: 2025,
    motor: "2.9L V6 Biturbo",
    potencia: "444 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 82000,
    color: "Azul Nogaro",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Audi Center Montevideo",
    descripcion: "Sportback de 5 puertas con tracción integral quattro y diseño coupé.",
    imagen: "https://imgs.search.brave.com/UvfkwBRvb_gXp96jTH7OV_lQDvc7NpJ-HjuvouIibJs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9hdWRp/LXJzNS1jb21wZXRp/dGlvbi1wYWNrYWdl/LTExLTE2NTIyODUx/ODIuanBnP2Nyb3A9/MC43MjN4dzowLjYw/OXhoOzAuMTY4eHcs/MC4yMjF4aCZyZXNp/emU9MTIwMDoq"
  },
  {
    id: 10,
    marca: "Nissan",
    modelo: "GT-R Nismo",
    anio: 2024,
    motor: "3.8L V6 Biturbo",
    potencia: "600 HP",
    combustible: "Nafta",
    transmision: "Automática de doble embrague 6 velocidades",
    precio: 225000,
    color: "Rojo Ultimate",
    kilometraje: 1200,
    condicion: "Usado - excelente estado",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Concesionario privado",
    descripcion: "Edición Nismo con componentes de carbono y suspensión afinada en Nürburgring.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 11,
    marca: "McLaren",
    modelo: "750S",
    anio: 2025,
    motor: "4.0L V8 Biturbo",
    potencia: "740 HP",
    combustible: "Nafta",
    transmision: "Automática de doble embrague 7 velocidades",
    precio: 335000,
    color: "Naranja Papaya",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Miami, Estados Unidos",
    vendedor: "McLaren Miami",
    descripcion: "Superdeportivo ligero con chasis de fibra de carbono MonoCell II.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 12,
    marca: "Chevrolet",
    modelo: "Corvette Z06",
    anio: 2025,
    motor: "5.5L V8 Atmosférico",
    potencia: "670 HP",
    combustible: "Nafta",
    transmision: "Automática de doble embrague",
    precio: 145000,
    color: "Amarillo Accelerate",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Miami, Estados Unidos",
    vendedor: "Chevrolet Performance Center",
    descripcion: "Superdeportivo de motor central con el V8 atmosférico más potente de GM.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 13,
    marca: "BMW",
    modelo: "M4 Competition",
    anio: 2025,
    motor: "3.0L TwinPower Turbo I6",
    potencia: "523 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 90000,
    color: "Isle of Man Green",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Punta del Este, Uruguay",
    vendedor: "BMW Motorrad Uruguay",
    descripcion: "Coupé deportivo con parrilla riñón, motor biturbo y suspensión adaptativa.",
    imagen: "https://imgs.search.brave.com/uyYkJ_MJfLC8aNTj-YZZOSxFdbvrhGWKACzATqQnfXY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL210Zy1wcm9k/LzY3ODU0YzRhM2Qz/NTcxMDAwOGFlMDFm/NC8wMDEtMjAyNC1j/YXJiYWhuLWJtdy1t/NC1mcm9udC10aHJl/ZS1xdWFydGVyLXN0/YXRpYy1sZWFkLmpw/Zz93PTc2OCZ3aWR0/aD03NjgmcT03NSZm/b3JtYXQ9d2VicA"
  },
  {
    id: 14,
    marca: "Subaru",
    modelo: "WRX STI",
    anio: 2023,
    motor: "2.5L Turbo Bóxer",
    potencia: "310 HP",
    combustible: "Nafta",
    transmision: "Manual 6 velocidades",
    precio: 42000,
    color: "Azul WR",
    kilometraje: 18000,
    condicion: "Usado - buen estado",
    ubicacion: "Maldonado, Uruguay",
    vendedor: "Particular",
    descripcion: "Tracción integral simétrica, ideal para rally y uso deportivo diario.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 15,
    marca: "Ferrari",
    modelo: "296 GTB",
    anio: 2025,
    motor: "3.0L V6 Biturbo Híbrido",
    potencia: "830 HP",
    combustible: "Híbrido",
    transmision: "Automática de doble embrague 8 velocidades",
    precio: 420000,
    color: "Rosso Corsa",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "San Pablo, Brasil",
    vendedor: "Ferrari Concessionaria São Paulo",
    descripcion: "Berlinetta de motor central con propulsión híbrida enchufable.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 16,
    marca: "Volkswagen",
    modelo: "Golf R",
    anio: 2025,
    motor: "2.0L TSI Turbo",
    potencia: "333 HP",
    combustible: "Nafta",
    transmision: "DSG 7 velocidades",
    precio: 51000,
    color: "Azul Lapiz",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Volkswagen Uruguay",
    descripcion: "Hatchback deportivo con tracción integral 4MOTION y modo drift.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 17,
    marca: "Mercedes-Benz",
    modelo: "AMG C63 S E Performance",
    anio: 2025,
    motor: "2.0L Turbo Híbrido",
    potencia: "671 HP",
    combustible: "Híbrido",
    transmision: "AMG Speedshift MCT",
    precio: 90000,
    color: "Gris Selenita",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Mercedes-Benz Punta Carretas",
    descripcion: "Híbrido enchufable con batería de alto voltaje y modo eléctrico puro.",
    imagen: "https://imgs.search.brave.com/JTeTegBhV82rndZ4PJbJgvuZCGowGTIPR4oYKyQFUgw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy8yMDIz/LW1lcmNlZGVzLWFt/Zy1jNjMtcy1lLXBl/cmZvcm1hbmNlLTEx/NC02NWQ3OTY5OGIw/ZTI2LmpwZz9jcm9w/PTAuNTkxeHc6MC40/OTl4aDswLjM5N3h3/LDAuNDIyeGgmcmVz/aXplPTcwMDoq"
  },
  {
    id: 18,
    marca: "Toyota",
    modelo: "GR Supra 3.0",
    anio: 2025,
    motor: "3.0L Turbo I6",
    potencia: "382 HP",
    combustible: "Nafta",
    transmision: "Manual / Automática",
    precio: 57000,
    color: "Naranja Renaissance",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Canelones, Uruguay",
    vendedor: "Toyota del Este",
    descripcion: "Coupé deportivo desarrollado junto a BMW, disponible con caja manual.",
    imagen: "https://imgs.search.brave.com/LD65Ndr9oko2WezzaWlwySbOtv9nupPJKAQMMoa1I0w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy8yMDI0/LXRveW90YS1nci1z/dXByYS00NXRoLWFu/bml2ZXJzYXJ5LWVk/aXRpb24tMTAzLTY0/OGNhZGM1ODQxNTEu/anBnP2Nyb3A9MXh3/OjAuODQzNzV4aDtj/ZW50ZXIsdG9wJnJl/c2l6ZT0xMjAwOio"
  },
  {
    id: 19,
    marca: "Audi",
    modelo: "RS7 Performance",
    anio: 2025,
    motor: "4.0L V8 Biturbo",
    potencia: "621 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 130000,
    color: "Ascari Blue",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "San Pablo, Brasil",
    vendedor: "Audi Center São Paulo",
    descripcion: "Sportback de gran tamaño con suspensión neumática adaptativa.",
    imagen: "https://imgs.search.brave.com/qntKtvx4pZE_TD4mio189oy9j6Q9emb6F53mYuXRTs8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL210Zy1wcm9k/LzY1YTFkM2UzOWFm/YTg2MDAwODEyNWMz/NS8yMDI0LWF1ZGkt/cnM3LXNwb3J0YmFj/ay1wZXJmb3JtYW5j/ZS1hc2NhcmktYmx1/ZS1tYXR0ZS1wYXNz/ZW5nZXItc2lkZS5q/cGc_dz03Njgmd2lk/dGg9NzY4JnE9NzUm/Zm9ybWF0PXdlYnA"
  },
  {
    id: 20,
    marca: "Lamborghini",
    modelo: "Temerario",
    anio: 2025,
    motor: "4.0L V8 Biturbo Híbrido",
    potencia: "907 HP",
    combustible: "Híbrido",
    transmision: "Automática 8 velocidades",
    precio: 360000,
    color: "Púrpura",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Buenos Aires, Argentina",
    vendedor: "Lamborghini Boutique (importación exclusiva)",
    descripcion: "Sucesor del Huracán, con motor V8 biturbo y sistema híbrido de alto rendimiento.",
    imagen: "https://imgs.search.brave.com/c9BtYKsmzlSx5B8sIZdh4kjo8QSJdPzttRXCp3C415Q/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMwLmNhcmJ1enpp/bWFnZXMuY29tL3dv/cmRwcmVzcy93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyNS8xMS8y/MDI2LWxhbWJvcmdo/aW5pLXRlbWVyYXJp/by1leHRlcmlvci1w/dXJwbGUtNy5qcGc_/cT00OSZmaXQ9Y3Jv/cCZ3PTQ4MCZkcHI9/Mg"
  },
  {
    id: 21,
    marca: "Porsche",
    modelo: "Cayenne Turbo GT",
    anio: 2025,
    motor: "4.0L V8 Biturbo",
    potencia: "650 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 205000,
    color: "Negro Metálico",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Santiago, Chile",
    vendedor: "Porsche Center Santiago",
    descripcion: "SUV deportiva de altas prestaciones, la más rápida de su segmento en pista.",
    imagen: "https://imgs.search.brave.com/i9IxiHfKOjrHDFFjTvOPsNq7xwUruwLY3LfjtOdUmAw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG5y/cy5pbnZlbnRvcnly/c2MuY29tLzY0MHg0/ODAvNTI0NTkyNDI1/XzZhMTk5YzZhNTYy/MDBjYzQ0NTBjYmNk/Yi5qcGc"
  },
  {
    id: 22,
    marca: "Tesla",
    modelo: "Model 3 Performance",
    anio: 2025,
    motor: "Dos motores eléctricos",
    potencia: "510 HP",
    combustible: "Eléctrico",
    transmision: "Automática",
    precio: 55000,
    color: "Rojo Multicapa",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Tesla Store (importación directa)",
    descripcion: "Sedán eléctrico compacto con tracción integral y gran autonomía.",
    imagen: "https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Model-3-Performance-Aero-Desktop.jpg"
  },
  {
    id: 23,
    marca: "Dodge",
    modelo: "Challenger SRT Hellcat",
    anio: 2023,
    motor: "6.2L V8 Sobrealimentado",
    potencia: "717 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 78000,
    color: "Naranja Go Mango",
    kilometraje: 9500,
    condicion: "Usado - excelente estado",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Particular",
    descripcion: "Muscle car con motor sobrealimentado, un clásico moderno del drag racing.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 24,
    marca: "Kia",
    modelo: "EV6 GT",
    anio: 2025,
    motor: "Dos motores eléctricos",
    potencia: "576 HP",
    combustible: "Eléctrico",
    transmision: "Automática",
    precio: 68000,
    color: "Verde Mighty Ocean",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Kia Uruguay",
    descripcion: "SUV eléctrica de altas prestaciones, 0-100 km/h en 3.5 segundos.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 25,
    marca: "Aston Martin",
    modelo: "Vantage",
    anio: 2025,
    motor: "4.0L V8 Biturbo",
    potencia: "656 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 195000,
    color: "Verde Racing",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Buenos Aires, Argentina",
    vendedor: "Aston Martin Buenos Aires",
    descripcion: "Deportivo británico con chasis de aluminio y motor Mercedes-AMG.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 26,
    marca: "Jeep",
    modelo: "Grand Cherokee Trackhawk",
    anio: 2022,
    motor: "6.2L V8 Sobrealimentado",
    potencia: "707 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 95000,
    color: "Negro Diamante",
    kilometraje: 22000,
    condicion: "Usado - buen estado",
    ubicacion: "Canelones, Uruguay",
    vendedor: "Particular",
    descripcion: "SUV con el motor supercargado del Hellcat, la más rápida de su categoría.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 27,
    marca: "Maserati",
    modelo: "MC20",
    anio: 2025,
    motor: "3.0L V6 Twin-Turbo",
    potencia: "630 HP",
    combustible: "Nafta",
    transmision: "Automática de doble embrague 8 velocidades",
    precio: 250000,
    color: "Blanco Audace",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "San Pablo, Brasil",
    vendedor: "Maserati São Paulo",
    descripcion: "Superdeportivo italiano con motor Nettuno desarrollado in-house.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 28,
    marca: "Hyundai",
    modelo: "Ioniq 5 N",
    anio: 2025,
    motor: "Dos motores eléctricos",
    potencia: "641 HP",
    combustible: "Eléctrico",
    transmision: "Automática",
    precio: 72000,
    color: "Azul Performance",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Hyundai Uruguay",
    descripcion: "Crossover eléctrico de alto rendimiento con simulación de cambios y sonido de motor.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 29,
    marca: "Chevrolet",
    modelo: "Camaro ZL1",
    anio: 2023,
    motor: "6.2L V8 Sobrealimentado",
    potencia: "650 HP",
    combustible: "Nafta",
    transmision: "Manual 6 velocidades",
    precio: 85000,
    color: "Amarillo Rally",
    kilometraje: 6000,
    condicion: "Usado - excelente estado",
    ubicacion: "Maldonado, Uruguay",
    vendedor: "Particular",
    descripcion: "Muscle car de altas prestaciones con paquete aerodinámico 1LE opcional.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 30,
    marca: "Alfa Romeo",
    modelo: "Giulia Quadrifoglio",
    anio: 2024,
    motor: "2.9L V6 Biturbo",
    potencia: "505 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 92000,
    color: "Rosso Competizione",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "Alfa Romeo Uruguay",
    descripcion: "Sedán deportivo con motor derivado de Ferrari y equilibrio de pesos ideal.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 31,
    marca: "BMW",
    modelo: "X5 M Competition",
    anio: 2025,
    motor: "4.4L V8 Biturbo",
    potencia: "617 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 145000,
    color: "Azul Marina Bay",
    kilometraje: 0,
    condicion: "0km",
    ubicacion: "Montevideo, Uruguay",
    vendedor: "BMW Motorrad Uruguay",
    descripcion: "SUV deportiva con tracción integral M xDrive y suspensión adaptativa.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  },
  {
    id: 32,
    marca: "Dodge",
    modelo: "Charger SRT Hellcat Redeye",
    anio: 2023,
    motor: "6.2L V8 Sobrealimentado",
    potencia: "797 HP",
    combustible: "Nafta",
    transmision: "Automática 8 velocidades",
    precio: 88000,
    color: "Rojo Octane",
    kilometraje: 4000,
    condicion: "Usado - excelente estado",
    ubicacion: "Buenos Aires, Argentina",
    vendedor: "Particular",
    descripcion: "Sedán muscle car, uno de los más potentes de producción de Dodge.",
    imagen: "https://imgs.search.brave.com/4sysyaB6WnitMH6ktswCotwtvb7WQI4m2OhRXhAtzD8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wbGF0/Zm9ybS5jc3RhdGlj/LWltYWdlcy5jb20v/aW4vdjIvc3RvY2tf/cGhvdG9zLzhhOTJm/NjA2LTE2ODYtNGJl/MS04M2I2LWQzZWE0/N2Y2YmE1NS81YTY3/M2VlYi0wNzk5LTQw/YzgtOGU4ZC1kZWMy/ZGMwNjQ5MTUucG5n"
  }
];

window.autos = autos;